version: 2

models:
  - name: stg_orders
    description: "Staging table containing order information."
    columns:
      - name: order_id
        description: "Unique identifier for each order."
        tests:
          - unique
          - not_null
      - name: customer_id
        description: "Unique identifier for the customer who placed the order."
        tests:
          - not_null
      - name: order_status
        description: "Current status of the order."
        tests:
          - accepted_values:
              values: ['delivered', 'shipped', 'canceled', 'unavailable', 'processing', 'invoiced', 'created', 'approved']

  - name: stg_order_items
    description: "Staging table containing items included in orders."
    columns:
      - name: order_id
        description: "Unique identifier for each order."
        tests:
          - not_null
      - name: product_id
        description: "Unique identifier for each product."
        tests:
          - not_null
      - name: seller_id
        description: "Unique identifier for each seller."
        tests:
          - not_null

  - name: stg_products
    description: "Staging table containing product information."
    columns:
      - name: product_id
        description: "Unique identifier for each product."
        tests:
          - unique
          - not_null

  - name: stg_customers
    description: "Staging table containing customer information."
    columns:
      - name: customer_id
        description: "Unique identifier for each customer."
        tests:
          - unique
          - not_null

  - name: fct_orders
    description: "Fact table containing detailed order information."
    columns:
      - name: order_id
        description: "Unique identifier for each order."
        tests:
          - unique
          - not_null
      - name: customer_id
        description: "Unique identifier for the customer who placed the order."
        tests:
          - not_null

  - name: dim_customers
    description: "Dimension table containing detailed customer information."
    columns:
      - name: customer_unique_id
        description: "Unique identifier for each customer in the dimension table."
        tests:
          - unique
          - not_null

  - name: dim_products
    description: "Dimension table containing detailed product information."
    columns:
      - name: product_id
        description: "Unique identifier for each product in the dimension table."
        tests:
          - unique
          - not_null

  - name: customer_stat_q3
    description: "Table containing customer statistics for Q3."
    columns:
      - name: customer_id
        description: "Unique identifier for each customer."
        tests:
          - unique
          - not_null
